import React, { useState } from 'react';
import { RiskResult } from '../types';
import { motion, AnimatePresence } from 'motion/react';
import { 
  ShieldAlert, ShieldCheck, ShieldQuestion, Stethoscope, User,
  CheckCircle2, AlertCircle, TrendingDown, ChevronRight, FileText
} from 'lucide-react';
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell,
  RadarChart, Radar, PolarGrid, PolarAngleAxis, PolarRadiusAxis,
  PieChart, Pie, Legend,
} from 'recharts';
import ReactMarkdown from 'react-markdown';
import { exportPatientReportPDF } from '../services/pdfExport';

interface RiskDashboardProps {
  result: RiskResult;
  patientInfo?: any;
}

const RISK_COLOR: Record<string, string> = {
  High: '#ef4444', Moderate: '#f59e0b', Low: '#10b981'
};

export default function RiskDashboard({ result, patientInfo }: RiskDashboardProps) {
  const [view, setView] = useState<'doctor' | 'patient'>('doctor');
  const [activeChart, setActiveChart] = useState<'bar' | 'radar'>('bar');
  const [isExporting, setIsExporting] = useState(false);

  const handleDownloadPDF = async () => {
    setIsExporting(true);
    try {
      await exportPatientReportPDF(result, patientInfo);
    } finally {
      setIsExporting(false);
    }
  };

  const getRiskColor = (category: string) => {
    switch (category) {
      case 'High': return 'text-red-600 bg-red-50 border-red-100';
      case 'Moderate': return 'text-amber-600 bg-amber-50 border-amber-100';
      default: return 'text-emerald-600 bg-emerald-50 border-emerald-100';
    }
  };

  const getRiskIcon = (category: string) => {
    switch (category) {
      case 'High': return ShieldAlert;
      case 'Moderate': return ShieldQuestion;
      default: return ShieldCheck;
    }
  };

  const RiskIcon = getRiskIcon(result.riskCategory);
  const riskColor = RISK_COLOR[result.riskCategory] ?? '#10b981';
  const gaugePercent = result.riskScore / 100;
  const gaugeDash = 2 * Math.PI * 54;

  const radarData = result.featureImportance.map(f => ({
    subject: f.feature.length > 12 ? f.feature.slice(0, 12) + '…' : f.feature,
    A: f.importance,
    fullMark: 100,
  }));

  const riskBreakdown = [
    { name: 'Risk Score', value: result.riskScore, fill: riskColor },
    { name: 'Safety Margin', value: 100 - result.riskScore, fill: '#e2e8f0' },
  ];

  return (
    <div className="space-y-6 max-w-6xl mx-auto pb-12">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-slate-900">Risk Assessment Report</h2>
          <p className="text-slate-500 text-sm">Generated by PreventAI Clinical Decision Support System</p>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <div className="bg-slate-100 p-1 rounded-2xl flex items-center shadow-inner">
            <button onClick={() => setView('doctor')} className={`flex items-center gap-2 px-5 py-2 rounded-xl text-sm font-bold transition-all ${view === 'doctor' ? 'bg-white text-emerald-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}>
              <Stethoscope className="w-4 h-4" /> Doctor View
            </button>
            <button onClick={() => setView('patient')} className={`flex items-center gap-2 px-5 py-2 rounded-xl text-sm font-bold transition-all ${view === 'patient' ? 'bg-white text-emerald-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}>
              <User className="w-4 h-4" /> Patient View
            </button>
          </div>
          <button
            onClick={handleDownloadPDF}
            disabled={isExporting}
            className="flex items-center gap-2 bg-emerald-600 text-white px-5 py-2.5 rounded-xl text-sm font-bold hover:bg-emerald-700 shadow-lg shadow-emerald-100 transition-all disabled:opacity-60"
          >
            {isExporting ? (
              <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
            ) : (
              <FileText className="w-4 h-4" />
            )}
            {isExporting ? 'Exporting PDF...' : 'Export PDF Report'}
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-1 space-y-5">
          <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="bg-white rounded-3xl p-6 border border-slate-200 shadow-sm">
            <div className={`inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-bold border ${getRiskColor(result.riskCategory)} mb-4`}>
              <RiskIcon className="w-3 h-3" />
              {result.riskCategory} Risk
            </div>
            <div className="flex justify-center mb-3">
              <svg width="150" height="150" viewBox="0 0 150 150">
                <circle cx="75" cy="75" r="54" fill="none" stroke="#e2e8f0" strokeWidth="14" />
                <circle
                  cx="75" cy="75" r="54" fill="none"
                  stroke={riskColor}
                  strokeWidth="14"
                  strokeDasharray={`${gaugePercent * gaugeDash} ${gaugeDash}`}
                  strokeLinecap="round"
                  transform="rotate(-90 75 75)"
                />
                <text x="75" y="69" textAnchor="middle" fontSize="26" fontWeight="bold" fill={riskColor}>{result.riskScore}</text>
                <text x="75" y="84" textAnchor="middle" fontSize="11" fill="#94a3b8">% Risk Score</text>
                <text x="75" y="99" textAnchor="middle" fontSize="10" fontWeight="bold" fill={riskColor}>{result.riskCategory}</text>
              </svg>
            </div>
            <p className="text-center text-slate-400 text-xs">Diabetes risk probability based on ML analysis</p>
          </motion.div>

          <div className="bg-white rounded-3xl p-5 border border-slate-200 shadow-sm">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2">
                <AlertCircle className="w-4 h-4 text-emerald-500" />
                Risk Contributors
              </h3>
              <div className="flex gap-1 bg-slate-100 rounded-lg p-0.5">
                {(['bar', 'radar'] as const).map(t => (
                  <button key={t} onClick={() => setActiveChart(t)} className={`px-2.5 py-1 rounded-md text-xs font-bold transition-all ${activeChart === t ? 'bg-white text-emerald-600 shadow-sm' : 'text-slate-400'}`}>
                    {t.charAt(0).toUpperCase() + t.slice(1)}
                  </button>
                ))}
              </div>
            </div>
            {activeChart === 'bar' && (
              <ResponsiveContainer width="100%" height={220}>
                <BarChart data={result.featureImportance} layout="vertical" margin={{ left: 0, right: 20, top: 5, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#f1f5f9" />
                  <XAxis type="number" hide />
                  <YAxis dataKey="feature" type="category" axisLine={false} tickLine={false} tick={{ fill: '#64748b', fontSize: 11 }} width={95} />
                  <Tooltip contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 10px 15px -3px rgb(0 0 0/0.1)', fontSize: '12px' }} formatter={(v: any) => [`${v}%`, 'Importance']} />
                  <Bar dataKey="importance" radius={[0, 5, 5, 0]} barSize={18} name="Importance (%)">
                    {result.featureImportance.map((_, i) => (
                      <Cell key={i} fill={i === 0 ? '#10b981' : i === 1 ? '#0d9488' : i === 2 ? '#3b82f6' : '#94a3b8'} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            )}
            {activeChart === 'radar' && (
              <ResponsiveContainer width="100%" height={220}>
                <RadarChart data={radarData}>
                  <PolarGrid stroke="#e2e8f0" />
                  <PolarAngleAxis dataKey="subject" tick={{ fontSize: 10, fill: '#64748b' }} />
                  <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} axisLine={false} />
                  <Radar name="Importance" dataKey="A" stroke="#10b981" fill="#10b981" fillOpacity={0.3} strokeWidth={2} />
                  <Tooltip contentStyle={{ borderRadius: '12px', border: 'none', fontSize: '12px' }} formatter={(v: any) => [`${v}%`]} />
                </RadarChart>
              </ResponsiveContainer>
            )}
          </div>

          <div className="bg-emerald-900 rounded-3xl p-6 text-white shadow-xl shadow-emerald-100">
            <h3 className="text-sm font-bold mb-4 flex items-center gap-2">
              <TrendingDown className="w-4 h-4" />
              Risk Reduction Insights
            </h3>
            <div className="space-y-3">
              {result.counterfactuals.map((text, i) => (
                <div key={i} className="flex gap-3 items-start">
                  <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-emerald-400 shrink-0" />
                  <p className="text-sm text-emerald-50/80 leading-relaxed">{text}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="lg:col-span-2 space-y-5">
          <AnimatePresence mode="wait">
            <motion.div key={view} initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden">
              <div className="p-7 border-b border-slate-100 bg-slate-50/30">
                <div className="flex items-center gap-3 mb-3">
                  {view === 'doctor' ? <Stethoscope className="w-5 h-5 text-emerald-600" /> : <User className="w-5 h-5 text-emerald-600" />}
                  <h3 className="text-lg font-bold text-slate-900">
                    {view === 'doctor' ? 'Clinical Assessment' : 'Personal Health Guide'}
                  </h3>
                </div>
                <div className="prose prose-slate prose-sm max-w-none text-slate-600 leading-relaxed">
                  <ReactMarkdown>{view === 'doctor' ? result.doctorView.explanation : result.patientView.explanation}</ReactMarkdown>
                </div>
              </div>

              <div className="p-7 grid grid-cols-1 md:grid-cols-2 gap-7">
                {view === 'doctor' ? (
                  <>
                    <section className="space-y-3">
                      <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest">Suggested Diagnostic Tests</h4>
                      {result.doctorView.diagnosticTests.map((test, i) => (
                        <div key={i} className="flex items-center gap-3 p-3 rounded-2xl bg-slate-50 border border-slate-100 text-sm text-slate-700 font-medium">
                          <div className="w-2 h-2 rounded-full bg-emerald-500 shrink-0" />
                          {test}
                        </div>
                      ))}
                    </section>
                    <section className="space-y-3">
                      <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest">Follow-up Recommendations</h4>
                      {result.doctorView.recommendations.map((rec, i) => (
                        <div key={i} className="flex items-center gap-3 p-3 rounded-2xl bg-emerald-50/50 border border-emerald-100 text-sm text-emerald-800 font-medium">
                          <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                          {rec}
                        </div>
                      ))}
                    </section>
                  </>
                ) : (
                  <>
                    <section className="space-y-3">
                      <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest">Lifestyle & Diet</h4>
                      <div className="p-4 rounded-2xl bg-amber-50 border border-amber-100">
                        <h5 className="text-xs font-bold text-amber-700 mb-2 uppercase">Dietary Suggestions</h5>
                        {result.patientView.dietSuggestions.map((item, i) => (
                          <p key={i} className="text-sm text-amber-900 flex gap-2 mb-1"><span className="text-amber-400">•</span>{item}</p>
                        ))}
                      </div>
                      <div className="p-4 rounded-2xl bg-blue-50 border border-blue-100">
                        <h5 className="text-xs font-bold text-blue-700 mb-2 uppercase">Lifestyle Advice</h5>
                        {result.patientView.lifestyleAdvice.map((item, i) => (
                          <p key={i} className="text-sm text-blue-900 flex gap-2 mb-1"><span className="text-blue-400">•</span>{item}</p>
                        ))}
                      </div>
                    </section>
                    <section className="space-y-3">
                      <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest">Exercise Plan</h4>
                      {result.patientView.exerciseRecommendations.map((rec, i) => (
                        <div key={i} className="flex items-center justify-between p-4 rounded-2xl bg-slate-50 border border-slate-100 group hover:border-emerald-200 transition-colors cursor-default">
                          <span className="text-sm text-slate-700 font-medium">{rec}</span>
                          <ChevronRight className="w-4 h-4 text-slate-300 group-hover:text-emerald-500 transition-colors" />
                        </div>
                      ))}
                    </section>
                  </>
                )}
              </div>
            </motion.div>
          </AnimatePresence>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            <div className="bg-white rounded-3xl p-5 border border-slate-200 shadow-sm">
              <h4 className="text-sm font-bold text-slate-900 mb-1">Risk vs Safety Margin</h4>
              <ResponsiveContainer width="100%" height={180}>
                <PieChart>
                  <Pie data={riskBreakdown} cx="50%" cy="50%" innerRadius={50} outerRadius={75} startAngle={90} endAngle={-270} dataKey="value" strokeWidth={0}>
                    {riskBreakdown.map((entry, i) => <Cell key={i} fill={entry.fill} />)}
                  </Pie>
                  <Tooltip formatter={(v: any) => [`${v}%`]} contentStyle={{ borderRadius: '12px', border: 'none', fontSize: '12px' }} />
                  <Legend iconType="circle" iconSize={8} wrapperStyle={{ fontSize: '11px' }} />
                </PieChart>
              </ResponsiveContainer>
            </div>

            <div className="bg-white rounded-3xl p-5 border border-slate-200 shadow-sm">
              <h4 className="text-sm font-bold text-slate-900 mb-3">Clinical Thresholds</h4>
              <div className="space-y-3">
                {[
                  { label: 'Your Risk Score', value: result.riskScore, color: riskColor },
                  { label: 'Avg. Population Risk', value: 32, color: '#94a3b8' },
                ].map((item, i) => (
                  <div key={i} className="space-y-1">
                    <div className="flex justify-between text-xs">
                      <span className="font-medium text-slate-600">{item.label}</span>
                      <span className="font-bold" style={{ color: item.color }}>{item.value}%</span>
                    </div>
                    <div className="h-3 bg-slate-100 rounded-full overflow-hidden">
                      <motion.div
                        initial={{ width: 0 }}
                        animate={{ width: `${item.value}%` }}
                        transition={{ duration: 1, delay: 0.3 + i * 0.2 }}
                        className="h-full rounded-full"
                        style={{ backgroundColor: item.color }}
                      />
                    </div>
                  </div>
                ))}
                <div className="mt-2 p-3 bg-slate-50 rounded-2xl border border-slate-100">
                  <div className="flex justify-between items-center text-xs mb-1">
                    <span className="text-slate-400">Risk Zones</span>
                    <div className="flex gap-3">
                      {[['Low', '#10b981'], ['Moderate', '#f59e0b'], ['High', '#ef4444']].map(([l, c]) => (
                        <span key={l} className="flex items-center gap-1 font-medium" style={{ color: c }}>
                          <span className="w-2 h-2 rounded-full inline-block" style={{ background: c }} />{l}
                        </span>
                      ))}
                    </div>
                  </div>
                  <div className="h-3 w-full rounded-full overflow-hidden flex">
                    <div className="bg-emerald-400" style={{ flex: 30 }} />
                    <div className="bg-amber-400" style={{ flex: 30 }} />
                    <div className="bg-red-400" style={{ flex: 40 }} />
                  </div>
                  <div className="flex justify-between text-[10px] text-slate-400 mt-0.5">
                    <span>0%</span><span>30%</span><span>60%</span><span>100%</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
