import React, { useState } from 'react';
import { RiskResult } from '../types';
import { motion, AnimatePresence } from 'motion/react';
import { 
  ShieldAlert, 
  ShieldCheck, 
  ShieldQuestion, 
  Stethoscope, 
  User, 
  ArrowRight, 
  CheckCircle2, 
  AlertCircle,
  TrendingDown,
  ChevronRight
} from 'lucide-react';
import RiskChart from './RiskChart';
import ReactMarkdown from 'react-markdown';

interface RiskDashboardProps {
  result: RiskResult;
}

export default function RiskDashboard({ result }: RiskDashboardProps) {
  const [view, setView] = useState<'doctor' | 'patient'>('doctor');

  const getRiskColor = (category: string) => {
    switch (category) {
      case 'High': return 'text-red-600 bg-red-50 border-red-100';
      case 'Moderate': return 'text-amber-600 bg-amber-50 border-amber-100';
      case 'Low': return 'text-emerald-600 bg-emerald-50 border-emerald-100';
      default: return 'text-slate-600 bg-slate-50 border-slate-100';
    }
  };

  const getRiskIcon = (category: string) => {
    switch (category) {
      case 'High': return ShieldAlert;
      case 'Moderate': return ShieldQuestion;
      case 'Low': return ShieldCheck;
      default: return ShieldCheck;
    }
  };

  const RiskIcon = getRiskIcon(result.riskCategory);

  return (
    <div className="space-y-6 max-w-6xl mx-auto pb-12">
      {/* Header with Toggle */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-slate-900">Risk Assessment Report</h2>
          <p className="text-slate-500">Generated by PreventAI Clinical Support System</p>
        </div>
        
        <div className="bg-slate-100 p-1 rounded-2xl flex items-center shadow-inner">
          <button
            onClick={() => setView('doctor')}
            className={`flex items-center gap-2 px-6 py-2.5 rounded-xl text-sm font-bold transition-all ${
              view === 'doctor' ? 'bg-white text-emerald-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'
            }`}
          >
            <Stethoscope className="w-4 h-4" />
            Doctor View
          </button>
          <button
            onClick={() => setView('patient')}
            className={`flex items-center gap-2 px-6 py-2.5 rounded-xl text-sm font-bold transition-all ${
              view === 'patient' ? 'bg-white text-emerald-600 shadow-sm' : 'text-slate-500 hover:text-slate-700'
            }`}
          >
            <User className="w-4 h-4" />
            Patient View
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column: Summary & Chart */}
        <div className="lg:col-span-1 space-y-6">
          {/* Risk Summary Card */}
          <motion.div 
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="bg-white rounded-3xl p-8 border border-slate-200 shadow-sm relative overflow-hidden"
          >
            <div className={`absolute top-0 right-0 w-32 h-32 -mr-8 -mt-8 rounded-full opacity-10 ${getRiskColor(result.riskCategory).split(' ')[1]}`} />
            
            <div className="relative">
              <div className={`inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-bold border ${getRiskColor(result.riskCategory)} mb-4`}>
                <RiskIcon className="w-3 h-3" />
                {result.riskCategory} Risk
              </div>
              
              <div className="flex items-baseline gap-1">
                <span className="text-6xl font-black text-slate-900 tracking-tighter">{result.riskScore}</span>
                <span className="text-2xl font-bold text-slate-400">%</span>
              </div>
              <p className="text-slate-500 font-medium mt-2">Diabetes Risk Score</p>
            </div>
          </motion.div>

          {/* Feature Importance */}
          <div className="bg-white rounded-3xl p-6 border border-slate-200 shadow-sm">
            <h3 className="text-sm font-bold text-slate-900 mb-6 flex items-center gap-2">
              <AlertCircle className="w-4 h-4 text-emerald-500" />
              Key Risk Contributors
            </h3>
            <RiskChart data={result.featureImportance} />
          </div>

          {/* Counterfactual Insights */}
          <div className="bg-emerald-900 rounded-3xl p-6 text-white shadow-xl shadow-emerald-100">
            <h3 className="text-sm font-bold mb-4 flex items-center gap-2">
              <TrendingDown className="w-4 h-4" />
              Risk Reduction Insights
            </h3>
            <div className="space-y-3">
              {result.counterfactuals.map((text, i) => (
                <div key={i} className="flex gap-3 items-start group">
                  <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-emerald-400 group-hover:scale-125 transition-transform" />
                  <p className="text-sm text-emerald-50/80 leading-relaxed">{text}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Right Column: Detailed View */}
        <div className="lg:col-span-2">
          <AnimatePresence mode="wait">
            <motion.div
              key={view}
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden min-h-[600px]"
            >
              <div className="p-8 border-b border-slate-100 bg-slate-50/30">
                <div className="flex items-center gap-3 mb-2">
                  {view === 'doctor' ? <Stethoscope className="w-5 h-5 text-emerald-600" /> : <User className="w-5 h-5 text-emerald-600" />}
                  <h3 className="text-lg font-bold text-slate-900">
                    {view === 'doctor' ? 'Clinical Assessment' : 'Personal Health Guide'}
                  </h3>
                </div>
                <div className="prose prose-slate prose-sm max-w-none text-slate-600 leading-relaxed">
                  <ReactMarkdown>
                    {view === 'doctor' ? result.doctorView.explanation : result.patientView.explanation}
                  </ReactMarkdown>
                </div>
              </div>

              <div className="p-8 grid grid-cols-1 md:grid-cols-2 gap-8">
                {view === 'doctor' ? (
                  <>
                    <section className="space-y-4">
                      <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest">Suggested Diagnostic Tests</h4>
                      <ul className="space-y-3">
                        {result.doctorView.diagnosticTests.map((test, i) => (
                          <li key={i} className="flex items-center gap-3 p-3 rounded-2xl bg-slate-50 border border-slate-100 text-sm text-slate-700 font-medium">
                            <div className="w-2 h-2 rounded-full bg-emerald-500" />
                            {test}
                          </li>
                        ))}
                      </ul>
                    </section>
                    <section className="space-y-4">
                      <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest">Follow-up Recommendations</h4>
                      <ul className="space-y-3">
                        {result.doctorView.recommendations.map((rec, i) => (
                          <li key={i} className="flex items-center gap-3 p-3 rounded-2xl bg-emerald-50/50 border border-emerald-100 text-sm text-emerald-800 font-medium">
                            <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                            {rec}
                          </li>
                        ))}
                      </ul>
                    </section>
                  </>
                ) : (
                  <>
                    <section className="space-y-4">
                      <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest">Lifestyle & Diet</h4>
                      <div className="space-y-4">
                        <div className="p-4 rounded-2xl bg-amber-50 border border-amber-100">
                          <h5 className="text-xs font-bold text-amber-700 mb-2 uppercase">Dietary Suggestions</h5>
                          <ul className="space-y-2">
                            {result.patientView.dietSuggestions.map((item, i) => (
                              <li key={i} className="text-sm text-amber-900 flex gap-2">
                                <span className="text-amber-400">•</span> {item}
                              </li>
                            ))}
                          </ul>
                        </div>
                        <div className="p-4 rounded-2xl bg-blue-50 border border-blue-100">
                          <h5 className="text-xs font-bold text-blue-700 mb-2 uppercase">Lifestyle Advice</h5>
                          <ul className="space-y-2">
                            {result.patientView.lifestyleAdvice.map((item, i) => (
                              <li key={i} className="text-sm text-blue-900 flex gap-2">
                                <span className="text-blue-400">•</span> {item}
                              </li>
                            ))}
                          </ul>
                        </div>
                      </div>
                    </section>
                    <section className="space-y-4">
                      <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest">Exercise Plan</h4>
                      <div className="space-y-3">
                        {result.patientView.exerciseRecommendations.map((rec, i) => (
                          <div key={i} className="flex items-center justify-between p-4 rounded-2xl bg-slate-50 border border-slate-100 group hover:border-emerald-200 transition-colors cursor-default">
                            <span className="text-sm text-slate-700 font-medium">{rec}</span>
                            <ChevronRight className="w-4 h-4 text-slate-300 group-hover:text-emerald-500 transition-colors" />
                          </div>
                        ))}
                      </div>
                    </section>
                  </>
                )}
              </div>
            </motion.div>
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
}
